"""Generated message classes for logging version v1beta3.

Google Cloud Logging API lets you create logs, ingest log entries, and manage
log sinks.
"""
# NOTE: This file is autogenerated and should not be edited by hand.

from protorpc import messages

from googlecloudapis.apitools.base.py import encoding


package = 'logging'


class Empty(messages.Message):
  """A generic empty message that you can re-use to avoid defining duplicated
  empty messages in your APIs. A typical example is to use it as the request
  or the response type of an API method. For instance:      service Foo {
  rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty);     }
  """



class Expression(messages.Message):
  """* Expression is one of the union of all filter expression types.  Note
  that some expression types (e.g., member, function, value, phrase) are only
  used in sub-expressions. For example, the filter expression "foo" is parsed
  and represented by a global restriction with the right hand side expression
  being the phrase.

  Fields:
    conjunction: * Represents an explicitly specified conjunction. Syntax:
      expr {AND expr} Example:  color=blue AND size>10 AND label:frontend
    disjunction: * Represents an explicitly specified disjunction. Syntax:
      expr {OR expr} Example:  color=blue OR color=red
    function: * Represents a function invocation. Syntax:    expr([expr {,
      expr}) Example:   argument(3)            argument("name")
      geopoint(50.0755381, 14.43780)
    member: * Represents a dot-separated path which can reference a field or
      map key. Syntax:    expr {.expr} Example:   field.child.grandchild
    negation: * Represents a negation of an expression. Syntax:   -expr
      NOT expr Example:  -frontend           NOT color=red
    phrase: * Represents a quoted string: a phrase. Example: "foo bar"
      "a.b.c"
    restriction: * Represents a restriction, either a binary, or unary
      (global) expression. Syntax:   expr [(operator) expr] Example:
      color:blue           frontend
    sequence: * Represents a sequence of restrictions, implicitly expressed
      conjunction: Syntax:   expr {expr} Example:  -frontend size>10 color=red
    value: * Represents a literal value. At a lexical level it can be a TEXT,
      OR, AND, or NOT.  Example:  frontend           3.14           $100
  """

  conjunction = messages.MessageField('ExpressionList', 1)
  disjunction = messages.MessageField('ExpressionList', 2)
  function = messages.MessageField('Function', 3)
  member = messages.MessageField('ExpressionList', 4)
  negation = messages.MessageField('Expression', 5)
  phrase = messages.MessageField('Phrase', 6)
  restriction = messages.MessageField('Restriction', 7)
  sequence = messages.MessageField('ExpressionList', 8)
  value = messages.StringField(9)


class ExpressionList(messages.Message):
  """* Represents a list of expressions, used for logical operators and
  chained, nested field access.

  Fields:
    expressions: A Expression attribute.
  """

  expressions = messages.MessageField('Expression', 1, repeated=True)


class Function(messages.Message):
  """* Represents a function call expression:   function([arg {, arg}])

  Fields:
    args: A Expression attribute.
    function: A Expression attribute.
  """

  args = messages.MessageField('Expression', 1, repeated=True)
  function = messages.MessageField('Expression', 2)


class ListLogEntriesResponse(messages.Message):
  """Result returned from `ListLogEntries`.

  Fields:
    entries: A list of log entry resources.  Fewer than `pageSize` entries may
      be returned, but that is not an indication that there are no more
      entries.
    nextPageToken: If there are more results, then `nextPageToken` is returned
      in the response.  To get the next batch of entries, use the value of
      `nextPageToken` as `pageToken` in the next call of `ListLogEntries`. If
      `nextPageToken` is empty, then there are no more results.
  """

  entries = messages.MessageField('LogEntry', 1, repeated=True)
  nextPageToken = messages.BytesField(2)


class ListLogMetricsResponse(messages.Message):
  """Result returned from ListLogMetrics.

  Fields:
    metrics: The list of metrics returned.
    nextPageToken: If non-empty, then there are more results. This token
      should be used in the next call to ListLogMetrics.
  """

  metrics = messages.MessageField('LogMetric', 1, repeated=True)
  nextPageToken = messages.StringField(2)


class ListLogServiceIndexesResponse(messages.Message):
  """Result returned from ListLogServiceIndexesRequest.

  Fields:
    nextPageToken: If there are more results, then `nextPageToken` is returned
      in the response.  To get the next batch of indexes, use the value of
      `nextPageToken` as `pageToken` in the next call of
      `ListLogServiceIndexes`. If `nextPageToken` is empty, then there are no
      more results.
    serviceIndexPrefixes: A list of log service index prefixes.
  """

  nextPageToken = messages.StringField(1)
  serviceIndexPrefixes = messages.StringField(2, repeated=True)


class ListLogServiceSinksResponse(messages.Message):
  """Result returned from `ListLogServiceSinks`.

  Fields:
    sinks: The requested log service sinks.  If any of the returned `LogSink`
      objects have an empty `destination` field, then call
      `logServices.sinks.get` to retrieve the complete `LogSink` object.
  """

  sinks = messages.MessageField('LogSink', 1, repeated=True)


class ListLogServicesResponse(messages.Message):
  """Result returned from `ListLogServicesRequest`.

  Fields:
    logServices: A list of log services.
    nextPageToken: If there are more results, then `nextPageToken` is returned
      in the response.  To get the next batch of services, use the value of
      `nextPageToken` as `pageToken` in the next call of `ListLogServices`. If
      `nextPageToken` is empty, then there are no more results.
  """

  logServices = messages.MessageField('LogService', 1, repeated=True)
  nextPageToken = messages.StringField(2)


class ListLogSinksResponse(messages.Message):
  """Result returned from `ListLogSinks`.

  Fields:
    sinks: The requested log sinks.  If any of the returned `LogSink` objects
      have an empty `destination` field, then call `logServices.sinks.get` to
      retrieve the complete `LogSink` object.
  """

  sinks = messages.MessageField('LogSink', 1, repeated=True)


class ListLogsResponse(messages.Message):
  """Result returned from ListLogs.

  Fields:
    logs: A list of log resources.
    nextPageToken: If there are more results, then `nextPageToken` is returned
      in the response.  To get the next batch of logs, use the value of
      `nextPageToken` as `pageToken` in the next call of `ListLogs`. If
      `nextPageToken` is empty, then there are no more results.
  """

  logs = messages.MessageField('Log', 1, repeated=True)
  nextPageToken = messages.StringField(2)


class Log(messages.Message):
  """A log object.

  Fields:
    displayName: Name used when displaying the log to the user (for example,
      in a UI). Example: `"activity_log"`
    name: REQUIRED: The log's name name. Example:
      `"compute.googleapis.com/activity_log"`.
    payloadType: Type URL describing the expected payload type for the log.
  """

  displayName = messages.StringField(1)
  name = messages.StringField(2)
  payloadType = messages.StringField(3)


class LogEntry(messages.Message):
  """An individual entry in a log.

  Messages:
    ProtoPayloadValue: The log entry payload, represented as a protocol buffer
      that is expressed as a JSON object. You can only pass `protoPayload`
      values that belong to a set of approved types.
    StructPayloadValue: The log entry payload, represented as a structure that
      is expressed as a JSON object.

  Fields:
    insertId: A unique ID for the log entry. If you provide this field, the
      logging service considers other log entries in the same log with the
      same ID as duplicates which can be removed.
    log: The log to which this entry belongs. When a log entry is ingested,
      the value of this field is set by the logging system.
    metadata: Information about the log entry.
    protoPayload: The log entry payload, represented as a protocol buffer that
      is expressed as a JSON object. You can only pass `protoPayload` values
      that belong to a set of approved types.
    structPayload: The log entry payload, represented as a structure that is
      expressed as a JSON object.
    textPayload: The log entry payload, represented as a text string.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class ProtoPayloadValue(messages.Message):
    """The log entry payload, represented as a protocol buffer that is
    expressed as a JSON object. You can only pass `protoPayload` values that
    belong to a set of approved types.

    Messages:
      AdditionalProperty: An additional property for a ProtoPayloadValue
        object.

    Fields:
      additionalProperties: Properties of the object. Contains field @ype with
        type URL.
    """

    class AdditionalProperty(messages.Message):
      """An additional property for a ProtoPayloadValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = messages.StringField(1)
      value = messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = messages.MessageField('AdditionalProperty', 1, repeated=True)

  @encoding.MapUnrecognizedFields('additionalProperties')
  class StructPayloadValue(messages.Message):
    """The log entry payload, represented as a structure that is expressed as
    a JSON object.

    Messages:
      AdditionalProperty: An additional property for a StructPayloadValue
        object.

    Fields:
      additionalProperties: Properties of the object.
    """

    class AdditionalProperty(messages.Message):
      """An additional property for a StructPayloadValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = messages.StringField(1)
      value = messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = messages.MessageField('AdditionalProperty', 1, repeated=True)

  insertId = messages.StringField(1)
  log = messages.StringField(2)
  metadata = messages.MessageField('LogEntryMetadata', 3)
  protoPayload = messages.MessageField('ProtoPayloadValue', 4)
  structPayload = messages.MessageField('StructPayloadValue', 5)
  textPayload = messages.StringField(6)


class LogEntryMetadata(messages.Message):
  """Additional data that is associated with a log entry, set by the service
  creating the log entry.

  Enums:
    SeverityValueValuesEnum: The severity of the log entry.

  Messages:
    LabelsValue: A set of (key, value) data that provides additional
      information about the log entry. If the log entry is from one of the
      Google Cloud Platform sources listed below, the indicated (key, value)
      information must be provided:  Google App Engine, service_name
      `appengine.googleapis.com`:        "appengine.googleapis.com/module_id",
      <module ID>       "appengine.googleapis.com/version_id", <version ID>
      and one of:       "appengine.googleapis.com/replica_index", <instance
      index>       "appengine.googleapis.com/clone_id", <instance ID>      or
      else provide the following Compute Engine labels:  Google Compute
      Engine, service_name `compute.googleapis.com`:
      "compute.googleapis.com/resource_type", "instance"
      "compute.googleapis.com/resource_id", <instance ID>

  Fields:
    labels: A set of (key, value) data that provides additional information
      about the log entry. If the log entry is from one of the Google Cloud
      Platform sources listed below, the indicated (key, value) information
      must be provided:  Google App Engine, service_name
      `appengine.googleapis.com`:        "appengine.googleapis.com/module_id",
      <module ID>       "appengine.googleapis.com/version_id", <version ID>
      and one of:       "appengine.googleapis.com/replica_index", <instance
      index>       "appengine.googleapis.com/clone_id", <instance ID>      or
      else provide the following Compute Engine labels:  Google Compute
      Engine, service_name `compute.googleapis.com`:
      "compute.googleapis.com/resource_type", "instance"
      "compute.googleapis.com/resource_id", <instance ID>
    projectId: The project ID of the Google Cloud Platform service that
      created the log entry.
    projectNumber: This field is populated by the API at ingestion time.
    region: The region name of the Google Cloud Platform service that created
      the log entry.  For example, `"us-central1"`.
    serviceName: The API name of the Google Cloud Platform service that
      created the log entry.  For example, `"compute.googleapis.com"`.
    severity: The severity of the log entry.
    timeNanos: A string attribute.
    timestamp: The time the event described by the log entry occurred.
      Timestamps must be later than January 1, 1970.
    userId: The fully-qualified email address of the authenticated user that
      performed or requested the action represented by the log entry. If the
      log entry does not apply to an action taken by an authenticated user,
      then the field should be empty.
    zone: The zone of the Google Cloud Platform service that created the log
      entry. For example, `"us-central1-a"`.
  """

  class SeverityValueValuesEnum(messages.Enum):
    """The severity of the log entry.

    Values:
      DEFAULT: The log entry has no assigned severity level.
      DEBUG: Debug or trace information.
      INFO: Routine information, such as ongoing status or performance.
      NOTICE: Normal but significant events, such as start up, shut down, or
        configuration.
      WARNING: Warning events might cause problems.
      ERROR: Error events are likely to cause problems.
      CRITICAL: Critical events cause more severe problems or brief outages.
      ALERT: A person must take an action immediately.
      EMERGENCY: One or more systems are unusable.
    """
    DEFAULT = 0
    DEBUG = 1
    INFO = 2
    NOTICE = 3
    WARNING = 4
    ERROR = 5
    CRITICAL = 6
    ALERT = 7
    EMERGENCY = 8

  @encoding.MapUnrecognizedFields('additionalProperties')
  class LabelsValue(messages.Message):
    """A set of (key, value) data that provides additional information about
    the log entry. If the log entry is from one of the Google Cloud Platform
    sources listed below, the indicated (key, value) information must be
    provided:  Google App Engine, service_name `appengine.googleapis.com`:
    "appengine.googleapis.com/module_id", <module ID>
    "appengine.googleapis.com/version_id", <version ID>           and one of:
    "appengine.googleapis.com/replica_index", <instance index>
    "appengine.googleapis.com/clone_id", <instance ID>      or else provide
    the following Compute Engine labels:  Google Compute Engine, service_name
    `compute.googleapis.com`:         "compute.googleapis.com/resource_type",
    "instance"        "compute.googleapis.com/resource_id", <instance ID>

    Messages:
      AdditionalProperty: An additional property for a LabelsValue object.

    Fields:
      additionalProperties: Additional properties of type LabelsValue
    """

    class AdditionalProperty(messages.Message):
      """An additional property for a LabelsValue object.

      Fields:
        key: Name of the additional property.
        value: A string attribute.
      """

      key = messages.StringField(1)
      value = messages.StringField(2)

    additionalProperties = messages.MessageField('AdditionalProperty', 1, repeated=True)

  labels = messages.MessageField('LabelsValue', 1)
  projectId = messages.StringField(2)
  projectNumber = messages.IntegerField(3)
  region = messages.StringField(4)
  serviceName = messages.StringField(5)
  severity = messages.EnumField('SeverityValueValuesEnum', 6)
  timeNanos = messages.IntegerField(7)
  timestamp = messages.StringField(8)
  userId = messages.StringField(9)
  zone = messages.StringField(10)


class LogError(messages.Message):
  """A problem in a sink or the sink's configuration.

  Fields:
    resource: The resource associated with the error. It may be different from
      the sink destination. For example, the sink may point to a BigQuery
      dataset, but the error may refer to a table resource inside the dataset.
    status: The description of the last error observed.
    timeNanos: The last time the error was observed, in nanoseconds since the
      Unix epoch.
  """

  resource = messages.StringField(1)
  status = messages.MessageField('Status', 2)
  timeNanos = messages.IntegerField(3)


class LogMetric(messages.Message):
  """An object that describes a collected metric associated with a particular
  log. Each LogEntry that matches the filter in this metric will increase the
  value of the metric by 1.

  Fields:
    description: Description of this metric.
    filter: A filter that is applied to a LogEntry that determines whether the
      given LogEntry matches this metric.
    name: The name of this metric. This is a user defined identifier for the
      resource. Allowed characters include letters, numbers, and: / \ $ - _ .
      + ! * ' () %
    projectId: Project ID of the project that this metric belongs to. The user
      does not need to set this value. It is automatically set when the metric
      is created.
  """

  description = messages.StringField(1)
  filter = messages.StringField(2)
  name = messages.StringField(3)
  projectId = messages.StringField(4)


class LogService(messages.Message):
  """A log service object.

  Fields:
    indexKeys: Label keys used when labeling log entries for this service. The
      order of the keys is significant, with higher priority keys coming
      earlier in the list.
    name: The service's name.
  """

  indexKeys = messages.StringField(1, repeated=True)
  name = messages.StringField(2)


class LogSink(messages.Message):
  """An object that describes where a log may be written.

  Fields:
    destination: The resource to send log entries to. The supported sink
      resource types are:  + Google Cloud Storage:
      `storage.googleapis.com/BUCKET` or   `BUCKET.storage.googleapis.com/` +
      Google BigQuery:
      `bigquery.googleapis.com/projects/PROJECT/datasets/DATASET`  Currently
      the Cloud Logging API supports at most one sink for each resource type
      per log or log service resource.
    errors: _Output only._ All active errors found for this sink.
    filter: One Platform filter. If provided, only the messages matching the
      filter will be published.
    name: The name of this sink. This is a client-assigned identifier for the
      resource. This is ignored by UpdateLogSink and UpdateLogServicesSink.
  """

  destination = messages.StringField(1)
  errors = messages.MessageField('LogError', 2, repeated=True)
  filter = messages.MessageField('Expression', 3)
  name = messages.StringField(4)


class LoggingProjectsLogEntriesListRequest(messages.Message):
  """A LoggingProjectsLogEntriesListRequest object.

  Fields:
    filter:  A filter specification.  The response includes only entries that
      are selected by `filter`.  If `filter` is empty, then all entries are
      selected.
    orderBy: Sort order.  The only `LogEntry` field supported for sorting is
      `metadata.timestamp` and the default order is ascending (from older to
      newer).  To have entries returned in the opposite (descending) order,
      set `orderBy` to `"metadata.timestamp desc"`.
    pageSize: The maximum number of entries to return per request.  Fewer
      entries may be returned, but that is not an indication that there are no
      more entries.
    pageToken: An opaque token, returned as `nextPageToken` by a prior
      `ListLogEntries` operation.  If `pageToken` is supplied, then the other
      fields of this request may be omitted, and the previous `ListLogEntries`
      operation is continued.
    projectsId: Part of `projectName`. The project resource from which to
      retrieve log entries, for example: `projects/my_project_id`.
  """

  filter = messages.StringField(1)
  orderBy = messages.StringField(2)
  pageSize = messages.IntegerField(3, variant=messages.Variant.INT32)
  pageToken = messages.BytesField(4)
  projectsId = messages.StringField(5, required=True)


class LoggingProjectsLogServicesIndexesListRequest(messages.Message):
  """A LoggingProjectsLogServicesIndexesListRequest object.

  Fields:
    depth: A limit to the number of levels of the index hierarchy that are
      expanded. If `depth` is 0, it defaults to the level specified by the
      prefix field (the number of slash separators). The default empty prefix
      implies a `depth` of 1. It is an error for `depth` to be any non-zero
      value less than the number of components in `indexPrefix`.
    indexPrefix: Restricts the indexes returned to be those with a specified
      prefix.  The prefix has the form `"/label_value/label_value/..."`, in
      order corresponding to the [`LogService
      indexKeys`][google.logging.v1.LogService.index_keys]. Non-empty prefixes
      must begin with `/` .  Example prefixes:  +  `"/myModule/"` retrieves
      App Engine versions associated with    `myModule`. The trailing slash
      terminates the value. +  `"/myModule"` retrieves App Engine modules with
      names beginning    with `myModule`. +  `""` retrieves all indexes.
    log: A log resource like `/projects/project_id/logs/log_name`, identifying
      the log for which to list service indexes.
    logServicesId: Part of `serviceName`. See documentation of `projectsId`.
    pageSize: The maximum number of log service index resources to return in
      one operation.
    pageToken: An opaque token, returned as `nextPageToken` by a prior
      `ListLogServiceIndexes` operation.  If `pageToken` is supplied, then the
      other fields of this request are ignored, and instead the previous
      `ListLogServiceIndexes` operation is continued.
    projectsId: Part of `serviceName`. A log service resource of the form
      `/projects/*/logServices/*`. The service indexes of the log service are
      returned. Example:
      `"/projects/myProj/logServices/appengine.googleapis.com"`.
  """

  depth = messages.IntegerField(1, variant=messages.Variant.INT32)
  indexPrefix = messages.StringField(2)
  log = messages.StringField(3)
  logServicesId = messages.StringField(4, required=True)
  pageSize = messages.IntegerField(5, variant=messages.Variant.INT32)
  pageToken = messages.StringField(6)
  projectsId = messages.StringField(7, required=True)


class LoggingProjectsLogServicesListRequest(messages.Message):
  """A LoggingProjectsLogServicesListRequest object.

  Fields:
    log: The name of the log resource whose services are to be listed. log for
      which to list services. When empty, all services are listed.
    pageSize: The maximum number of `LogService` objects to return in one
      operation.
    pageToken: An opaque token, returned as `nextPageToken` by a prior
      `ListLogServices` operation.  If `pageToken` is supplied, then the other
      fields of this request are ignored, and instead the previous
      `ListLogServices` operation is continued.
    projectsId: Part of `projectName`. The project resource whose services are
      to be listed.
  """

  log = messages.StringField(1)
  pageSize = messages.IntegerField(2, variant=messages.Variant.INT32)
  pageToken = messages.StringField(3)
  projectsId = messages.StringField(4, required=True)


class LoggingProjectsLogServicesSinksCreateRequest(messages.Message):
  """A LoggingProjectsLogServicesSinksCreateRequest object.

  Fields:
    logServicesId: Part of `serviceName`. See documentation of `projectsId`.
    logSink: A LogSink resource to be passed as the request body.
    projectsId: Part of `serviceName`. The name of the service in which to
      create a sink.
  """

  logServicesId = messages.StringField(1, required=True)
  logSink = messages.MessageField('LogSink', 2)
  projectsId = messages.StringField(3, required=True)


class LoggingProjectsLogServicesSinksDeleteRequest(messages.Message):
  """A LoggingProjectsLogServicesSinksDeleteRequest object.

  Fields:
    logServicesId: Part of `sinkName`. See documentation of `projectsId`.
    projectsId: Part of `sinkName`. The name of the sink to delete.
    sinksId: Part of `sinkName`. See documentation of `projectsId`.
  """

  logServicesId = messages.StringField(1, required=True)
  projectsId = messages.StringField(2, required=True)
  sinksId = messages.StringField(3, required=True)


class LoggingProjectsLogServicesSinksGetRequest(messages.Message):
  """A LoggingProjectsLogServicesSinksGetRequest object.

  Fields:
    logServicesId: Part of `sinkName`. See documentation of `projectsId`.
    projectsId: Part of `sinkName`. The name of the sink to return.
    sinksId: Part of `sinkName`. See documentation of `projectsId`.
  """

  logServicesId = messages.StringField(1, required=True)
  projectsId = messages.StringField(2, required=True)
  sinksId = messages.StringField(3, required=True)


class LoggingProjectsLogServicesSinksListRequest(messages.Message):
  """A LoggingProjectsLogServicesSinksListRequest object.

  Fields:
    logServicesId: Part of `serviceName`. See documentation of `projectsId`.
    projectsId: Part of `serviceName`. The name of the service for which to
      list sinks.
  """

  logServicesId = messages.StringField(1, required=True)
  projectsId = messages.StringField(2, required=True)


class LoggingProjectsLogServicesSinksUpdateRequest(messages.Message):
  """A LoggingProjectsLogServicesSinksUpdateRequest object.

  Fields:
    logServicesId: Part of `sinkName`. See documentation of `projectsId`.
    logSink: A LogSink resource to be passed as the request body.
    projectsId: Part of `sinkName`. The name of the sink to update.
    sinksId: Part of `sinkName`. See documentation of `projectsId`.
  """

  logServicesId = messages.StringField(1, required=True)
  logSink = messages.MessageField('LogSink', 2)
  projectsId = messages.StringField(3, required=True)
  sinksId = messages.StringField(4, required=True)


class LoggingProjectsLogsDeleteRequest(messages.Message):
  """A LoggingProjectsLogsDeleteRequest object.

  Fields:
    logsId: Part of `logName`. See documentation of `projectsId`.
    projectsId: Part of `logName`. The log resource to delete.
  """

  logsId = messages.StringField(1, required=True)
  projectsId = messages.StringField(2, required=True)


class LoggingProjectsLogsEntriesWriteRequest(messages.Message):
  """A LoggingProjectsLogsEntriesWriteRequest object.

  Fields:
    logsId: Part of `logName`. See documentation of `projectsId`.
    projectsId: Part of `logName`. The name of the log resource into which to
      insert the log entries.
    writeLogEntriesRequest: A WriteLogEntriesRequest resource to be passed as
      the request body.
  """

  logsId = messages.StringField(1, required=True)
  projectsId = messages.StringField(2, required=True)
  writeLogEntriesRequest = messages.MessageField('WriteLogEntriesRequest', 3)


class LoggingProjectsLogsListRequest(messages.Message):
  """A LoggingProjectsLogsListRequest object.

  Fields:
    pageSize: The maximum number of results to return.
    pageToken: An opaque token, returned as `nextPageToken` by a prior
      `ListLogs` operation.  If `pageToken` is supplied, then the other fields
      of this request are ignored, and instead the previous `ListLogs`
      operation is continued.
    projectsId: Part of `projectName`. The project name for which to list the
      log resources.
    serviceIndexPrefix: A log service index prefix for which to list logs.
      Only logs containing entries whose metadata that includes these label
      values (associated with index keys) are returned. The prefix is a slash
      separated list of values, and need not specify all index labels. An
      empty index (or a single slash) matches all log service indexes.
    serviceName: A service name for which to list logs. Only logs containing
      entries whose metadata includes this service name are returned. If
      `serviceName` and `serviceIndexPrefix` are both empty, then all log
      names are returned.  To list all log names, regardless of service, leave
      both the `serviceName` and `serviceIndexPrefix` empty. To list log names
      containing entries with a particular service name (or explicitly empty
      service name) set `serviceName` to the desired value and
      `serviceIndexPrefix` to `"/"`.
  """

  pageSize = messages.IntegerField(1, variant=messages.Variant.INT32)
  pageToken = messages.StringField(2)
  projectsId = messages.StringField(3, required=True)
  serviceIndexPrefix = messages.StringField(4)
  serviceName = messages.StringField(5)


class LoggingProjectsLogsSinksCreateRequest(messages.Message):
  """A LoggingProjectsLogsSinksCreateRequest object.

  Fields:
    logSink: A LogSink resource to be passed as the request body.
    logsId: Part of `logName`. See documentation of `projectsId`.
    projectsId: Part of `logName`. The log in which to create a sink resource.
  """

  logSink = messages.MessageField('LogSink', 1)
  logsId = messages.StringField(2, required=True)
  projectsId = messages.StringField(3, required=True)


class LoggingProjectsLogsSinksDeleteRequest(messages.Message):
  """A LoggingProjectsLogsSinksDeleteRequest object.

  Fields:
    logsId: Part of `sinkName`. See documentation of `projectsId`.
    projectsId: Part of `sinkName`. The name of the sink to delete.
    sinksId: Part of `sinkName`. See documentation of `projectsId`.
  """

  logsId = messages.StringField(1, required=True)
  projectsId = messages.StringField(2, required=True)
  sinksId = messages.StringField(3, required=True)


class LoggingProjectsLogsSinksGetRequest(messages.Message):
  """A LoggingProjectsLogsSinksGetRequest object.

  Fields:
    logsId: Part of `sinkName`. See documentation of `projectsId`.
    projectsId: Part of `sinkName`. The name of the sink resource to return.
    sinksId: Part of `sinkName`. See documentation of `projectsId`.
  """

  logsId = messages.StringField(1, required=True)
  projectsId = messages.StringField(2, required=True)
  sinksId = messages.StringField(3, required=True)


class LoggingProjectsLogsSinksListRequest(messages.Message):
  """A LoggingProjectsLogsSinksListRequest object.

  Fields:
    logsId: Part of `logName`. See documentation of `projectsId`.
    projectsId: Part of `logName`. The log for which to list sinks.
  """

  logsId = messages.StringField(1, required=True)
  projectsId = messages.StringField(2, required=True)


class LoggingProjectsLogsSinksUpdateRequest(messages.Message):
  """A LoggingProjectsLogsSinksUpdateRequest object.

  Fields:
    logSink: A LogSink resource to be passed as the request body.
    logsId: Part of `sinkName`. See documentation of `projectsId`.
    projectsId: Part of `sinkName`. The name of the sink to update.
    sinksId: Part of `sinkName`. See documentation of `projectsId`.
  """

  logSink = messages.MessageField('LogSink', 1)
  logsId = messages.StringField(2, required=True)
  projectsId = messages.StringField(3, required=True)
  sinksId = messages.StringField(4, required=True)


class LoggingProjectsMetricsCreateRequest(messages.Message):
  """A LoggingProjectsMetricsCreateRequest object.

  Fields:
    logMetric: A LogMetric resource to be passed as the request body.
    projectsId: Part of `projectName`. The project in which to create a
      metric.
  """

  logMetric = messages.MessageField('LogMetric', 1)
  projectsId = messages.StringField(2, required=True)


class LoggingProjectsMetricsDeleteRequest(messages.Message):
  """A LoggingProjectsMetricsDeleteRequest object.

  Fields:
    metricsId: Part of `metricName`. See documentation of `projectsId`.
    projectsId: Part of `metricName`. The metric to delete.
  """

  metricsId = messages.StringField(1, required=True)
  projectsId = messages.StringField(2, required=True)


class LoggingProjectsMetricsGetRequest(messages.Message):
  """A LoggingProjectsMetricsGetRequest object.

  Fields:
    metricsId: Part of `metricName`. See documentation of `projectsId`.
    projectsId: Part of `metricName`. The metric to return.
  """

  metricsId = messages.StringField(1, required=True)
  projectsId = messages.StringField(2, required=True)


class LoggingProjectsMetricsListRequest(messages.Message):
  """A LoggingProjectsMetricsListRequest object.

  Fields:
    pageSize: Maximum number of results to return.
    pageToken: If non-empty, specifies from where to start returning results.
      This page_token is from a previous call to ListLogsMetrics.
    projectsId: Part of `projectName`. The project name for which to list
      metrics.
  """

  pageSize = messages.IntegerField(1, variant=messages.Variant.INT32)
  pageToken = messages.StringField(2)
  projectsId = messages.StringField(3, required=True)


class LoggingProjectsMetricsUpdateRequest(messages.Message):
  """A LoggingProjectsMetricsUpdateRequest object.

  Fields:
    logMetric: A LogMetric resource to be passed as the request body.
    metricsId: Part of `metricName`. See documentation of `projectsId`.
    projectsId: Part of `metricName`. The metric to update.
  """

  logMetric = messages.MessageField('LogMetric', 1)
  metricsId = messages.StringField(2, required=True)
  projectsId = messages.StringField(3, required=True)


class Phrase(messages.Message):
  """* Phrase is a quoted string literal split up into lexical tokens.
  Example:   "foo bar:" will be represented as:   values: "foo"   values: " "
  // whitespace   values: "bar"   values: ":"

  Fields:
    values: A string attribute.
  """

  values = messages.StringField(1, repeated=True)


class Restriction(messages.Message):
  """* Represents a restriction expression:   lhs (operator) rhs  For example:
  color:blue   size > 300   vm.started > argument("date")  Example of global
  restriction:   frontend  -labels.backend

  Enums:
    ComparatorValueValuesEnum:

  Fields:
    comparator: A ComparatorValueValuesEnum attribute.
    lhs: * Left hand side of the restriction comparison. Unset for unary
      (GLOBAL) restriction.
    rhs: * Right hand side of the binary comparisons. This value is always
      set, even for unary (GLOBAL) restriction.
  """

  class ComparatorValueValuesEnum(messages.Enum):
    """ComparatorValueValuesEnum enum type.

    Values:
      COMPARATOR_UNSPECIFIED: <no description>
      GLOBAL: * Global restriction. Global restriction is not associated with
        any field. Example:   blue
      HAS: * Set membership, string prefix matching: Syntax:    lhs: rhs
        Example:   color: blue            name: New*
      EQUALS: * Equality: Syntax:    lhs = rhs Example:   color = blue
      NOT_EQUALS: * Inequality: Syntax:    lhs != rhs Example:   color != blue
      LESS_THAN: * Strict less than comparison: Syntax:   lhs < rhs Example:
        size < 100
      LESS_THAN_EQUALS: * Less than or equals comparison: Syntax:   lhs <= rhs
        Example:  size <= 100
      GREATER_THAN: * Strict greater than comparison: Syntax:   lhs > rhs
        Example:  size > 10
      GREATER_THAN_EQUALS: * Greater than or equals comparison: Syntax:   lhs
        >= rhs Example:  size >= 10
    """
    COMPARATOR_UNSPECIFIED = 0
    GLOBAL = 1
    HAS = 2
    EQUALS = 3
    NOT_EQUALS = 4
    LESS_THAN = 5
    LESS_THAN_EQUALS = 6
    GREATER_THAN = 7
    GREATER_THAN_EQUALS = 8

  comparator = messages.EnumField('ComparatorValueValuesEnum', 1)
  lhs = messages.MessageField('Expression', 2)
  rhs = messages.MessageField('Expression', 3)


class StandardQueryParameters(messages.Message):
  """Query parameters accepted by all methods.

  Enums:
    FXgafvValueValuesEnum: V1 error format.
    AltValueValuesEnum: Data format for response.

  Fields:
    f__xgafv: V1 error format.
    access_token: OAuth access token.
    alt: Data format for response.
    bearer_token: OAuth bearer token.
    callback: JSONP
    fields: Selector specifying which fields to include in a partial response.
    key: API key. Your API key identifies your project and provides you with
      API access, quota, and reports. Required unless you provide an OAuth 2.0
      token.
    oauth_token: OAuth 2.0 token for the current user.
    pp: Pretty-print response.
    prettyPrint: Returns response with indentations and line breaks.
    quotaUser: Available to use for quota purposes for server-side
      applications. Can be any arbitrary string assigned to a user, but should
      not exceed 40 characters.
    trace: A tracing token of the form "token:<tokenid>" or "email:<ldap>" to
      include in api requests.
  """

  class AltValueValuesEnum(messages.Enum):
    """Data format for response.

    Values:
      json: Responses with Content-Type of application/json
      media: Media download with context-dependent Content-Type
      proto: Responses with Content-Type of application/x-protobuf
    """
    json = 0
    media = 1
    proto = 2

  class FXgafvValueValuesEnum(messages.Enum):
    """V1 error format.

    Values:
      _1: v1 error format
      _2: v2 error format
    """
    _1 = 0
    _2 = 1

  f__xgafv = messages.EnumField('FXgafvValueValuesEnum', 1)
  access_token = messages.StringField(2)
  alt = messages.EnumField('AltValueValuesEnum', 3, default=u'json')
  bearer_token = messages.StringField(4)
  callback = messages.StringField(5)
  fields = messages.StringField(6)
  key = messages.StringField(7)
  oauth_token = messages.StringField(8)
  pp = messages.BooleanField(9, default=True)
  prettyPrint = messages.BooleanField(10, default=True)
  quotaUser = messages.StringField(11)
  trace = messages.StringField(12)


class Status(messages.Message):
  """The `Status` defines a logical error model that is suitable for different
  programming environments, including REST APIs and RPC APIs. It is used by
  [gRPC](https://github.com/grpc). The error model is designed to be:  -
  Simple to use and understand for most users. - Flexible enough to meet
  unexpected needs.  # Overview The `Status` message contains 3 pieces of
  data: error code, error message, and error details. The error code should be
  an enum value of [google.rpc.Code][], but it may accept additional error
  codes if needed.  The error message should be a developer-facing English
  message that helps developers *understand* and *resolve* the error. If a
  localized user-facing error message is needed, it can be sent in the error
  details or localized by the client. The optional error details may contain
  arbitrary information about the error. There is a predefined set of error
  detail types in the package `google.rpc` which can be used for common error
  conditions.  # Language mapping The `Status` message is the logical
  representation of the error model, but it is not necessarily the actual wire
  format. When the `Status` message is exposed in different client libraries
  and different wire protocols, it can be mapped differently. For example, it
  will likely be mapped to some exceptions in Java, but more likely mapped to
  some error codes in C.  # Other uses The error model and the `Status`
  message can be used in a variety of environments - either with or without
  APIs - to provide consistent developer experience across different
  environments.  Example uses of this error model include:  - Partial errors.
  If a service needs to return partial errors to the client,     it may embed
  the `Status` in the normal response to indicate the partial     errors.  -
  Workflow errors. A typical workflow has multiple steps. Each step may
  have a `Status` message for error reporting purpose.  - Batch operations. If
  a client uses batch request and batch response, the     `Status` message
  should be used directly inside batch response, one for     each error sub-
  response.  - Asynchronous operations. If an API call embeds asynchronous
  operation     results in its response, the status of those operations should
  be     represented directly using the `Status` message.  - Logging. If some
  API errors are stored in logs, the message `Status` could     be used
  directly after any stripping needed for security/privacy reasons.

  Messages:
    DetailsValueListEntry: A DetailsValueListEntry object.

  Fields:
    code: The status code, which should be an enum value of
      [google.rpc.Code][].
    details: A list of messages that carry the error details.  There will be a
      common set of message types for APIs to use.
    message: A developer-facing error message, which should be in English. Any
      user-facing error message should be localized and sent in the
      [google.rpc.Status.details][google.rpc.Status.details] field, or
      localized by the client.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class DetailsValueListEntry(messages.Message):
    """A DetailsValueListEntry object.

    Messages:
      AdditionalProperty: An additional property for a DetailsValueListEntry
        object.

    Fields:
      additionalProperties: Properties of the object. Contains field @ype with
        type URL.
    """

    class AdditionalProperty(messages.Message):
      """An additional property for a DetailsValueListEntry object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = messages.StringField(1)
      value = messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = messages.MessageField('AdditionalProperty', 1, repeated=True)

  code = messages.IntegerField(1, variant=messages.Variant.INT32)
  details = messages.MessageField('DetailsValueListEntry', 2, repeated=True)
  message = messages.StringField(3)


class WriteLogEntriesRequest(messages.Message):
  """The parameters to WriteLogEntries.

  Messages:
    CommonLabelsValue: Metadata labels that apply to all log entries in this
      request, so that you don't have to repeat them in each log entry's
      `metadata.labels` field.  If any of the log entries contains a (key,
      value) with the same key that is in `commonLabels`, then the entry's
      (key, value) overrides the one in `commonLabels`.

  Fields:
    commonLabels: Metadata labels that apply to all log entries in this
      request, so that you don't have to repeat them in each log entry's
      `metadata.labels` field.  If any of the log entries contains a (key,
      value) with the same key that is in `commonLabels`, then the entry's
      (key, value) overrides the one in `commonLabels`.
    entries: Log entries to insert.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class CommonLabelsValue(messages.Message):
    """Metadata labels that apply to all log entries in this request, so that
    you don't have to repeat them in each log entry's `metadata.labels` field.
    If any of the log entries contains a (key, value) with the same key that
    is in `commonLabels`, then the entry's (key, value) overrides the one in
    `commonLabels`.

    Messages:
      AdditionalProperty: An additional property for a CommonLabelsValue
        object.

    Fields:
      additionalProperties: Additional properties of type CommonLabelsValue
    """

    class AdditionalProperty(messages.Message):
      """An additional property for a CommonLabelsValue object.

      Fields:
        key: Name of the additional property.
        value: A string attribute.
      """

      key = messages.StringField(1)
      value = messages.StringField(2)

    additionalProperties = messages.MessageField('AdditionalProperty', 1, repeated=True)

  commonLabels = messages.MessageField('CommonLabelsValue', 1)
  entries = messages.MessageField('LogEntry', 2, repeated=True)


class WriteLogEntriesResponse(messages.Message):
  """Result returned from WriteLogEntries.
empty"""


encoding.AddCustomJsonEnumMapping(
    StandardQueryParameters.FXgafvValueValuesEnum, '_1', '1')
encoding.AddCustomJsonEnumMapping(
    StandardQueryParameters.FXgafvValueValuesEnum, '_2', '2')
encoding.AddCustomJsonFieldMapping(
    StandardQueryParameters, 'f__xgafv', '$.xgafv')
